# Configure Compositions
namespace:
  # Enables Compositions
  create: false
  # General Information for nsi and kubeconfig creation
  cluster:
    name: ""
    aksapi: ""
    subscriptionid: ""
    location: "germanywestcentral"
  # Pattern to which namespace names must comply
  namePattern: "^(cx-)"