# Common Values
namespaceName: ""
clusterName: ""

# Creation of ServiceAccounts and ClusterRolebindings
createDefault: true
createReadOnly: true
createPrivileged: false # For legacy namespaces which still use privileged

kubeconfig:
  # Enables creation job for kubeconfigs
  create: true
  # Namespace where kubeconfig secrets are created -> If empty defaults to user namespace!
  namespace: ""
  # Namespace where the kubeconfig creation job is run
  jobNamespace: enerkube-custom

# Endpoint for kubeconfig creation, e.g. 
aksApi: ""

managementNamespace: false

# Enables default kyverno policies
ManagedNamespace: "true"

AdditionalLabels: {}
  # key1: value1
  # key2: value2

# Allow read of pods and pod logs in kube-system from default-service-account
allowKubesystem: false

# NamespaceInfo Values:
namespaceinfo:
  subscriptionId: ""
  Alerting: []
  cloudProvider: "Azure"
  location: "germanywestcentral"
  Responsible: "None"

permissions:
  view: []
    # - namespace: test
    #   serviceAccount: read-only
    # - namespace: test2
    #   serviceAccount: read-only
  edit: []
    # - namespace: test
    #   serviceAccount: default-login-serviceaccount