apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: irsa-runtimeconfig-provider-aws-efs
spec:
  serviceAccountTemplate:
    metadata:
      name: enerkube-provider-aws-provider-aws-efs
      annotations:
        eks.amazonaws.com/role-arn: {{ ( printf "arn:aws:iam::%s:role/enerkube_CROSSPLANE_ACCOUNT_ROLE_%s" (.Values.accountId | toString ) .Values.clusterName | quote )  }}
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers:
          - name: package-runtime
            resources:
              requests:
                memory: 100m
          priorityClassName: system-cluster-critical
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: irsa-runtimeconfig-provider-aws-ec2
spec:
  serviceAccountTemplate:
    metadata:
      name: enerkube-provider-aws-provider-aws-ec2
      annotations:
        eks.amazonaws.com/role-arn: {{ ( printf "arn:aws:iam::%s:role/enerkube_CROSSPLANE_ACCOUNT_ROLE_%s" (.Values.accountId | toString ) .Values.clusterName | quote )  }}
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers:
          - name: package-runtime
            resources:
              requests:
                memory: 100m
          priorityClassName: system-cluster-critical
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: irsa-runtimeconfig-provider-aws-backup
spec:
  serviceAccountTemplate:
    metadata:
      name: enerkube-provider-aws-provider-aws-backup
      annotations:
        eks.amazonaws.com/role-arn: {{ ( printf "arn:aws:iam::%s:role/enerkube_CROSSPLANE_ACCOUNT_ROLE_%s" (.Values.accountId | toString ) .Values.clusterName | quote )  }}
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers:
          - name: package-runtime
            resources:
              requests:
                memory: 100m
          priorityClassName: system-cluster-critical
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: irsa-runtimeconfig-provider-aws-kms
spec:
  serviceAccountTemplate:
    metadata:
      name: enerkube-provider-aws-provider-aws-kms
      annotations:
        eks.amazonaws.com/role-arn: {{ ( printf "arn:aws:iam::%s:role/enerkube_CROSSPLANE_ACCOUNT_ROLE_%s" (.Values.accountId | toString ) .Values.clusterName | quote )  }}
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers:
          - name: package-runtime
            resources:
              requests:
                memory: 100m
          priorityClassName: system-cluster-critical
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: irsa-runtimeconfig-provider-aws-iam
spec:
  serviceAccountTemplate:
    metadata:
      name: enerkube-provider-aws-provider-aws-iam
      annotations:
        eks.amazonaws.com/role-arn: {{ ( printf "arn:aws:iam::%s:role/enerkube_CROSSPLANE_ACCOUNT_ROLE_%s" (.Values.accountId | toString ) .Values.clusterName | quote )  }}
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers:
          - name: package-runtime
            resources:
              requests:
                memory: 100m
          priorityClassName: system-cluster-critical
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: irsa-runtimeconfig-provider-aws-s3
spec:
  serviceAccountTemplate:
    metadata:
      name: enerkube-provider-aws-provider-aws-s3
      annotations:
        eks.amazonaws.com/role-arn: {{ ( printf "arn:aws:iam::%s:role/enerkube_CROSSPLANE_ACCOUNT_ROLE_%s" (.Values.accountId | toString ) .Values.clusterName | quote )  }}
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers:
          - name: package-runtime
            resources:
              requests:
                memory: 100m
          priorityClassName: system-cluster-critical
{{- if .Values.providers.rds }}
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: irsa-runtimeconfig-provider-aws-rds
spec:
  serviceAccountTemplate:
    metadata:
      name: enerkube-provider-aws-provider-aws-rds
      annotations:
        eks.amazonaws.com/role-arn: {{ ( printf "arn:aws:iam::%s:role/enerkube_CROSSPLANE_ACCOUNT_ROLE_%s" (.Values.accountId | toString ) .Values.clusterName | quote )  }}
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers:
          - name: package-runtime
            resources:
              requests:
                memory: 100m
          priorityClassName: system-cluster-critical
{{- end }}
