{{- $ResourceName := printf "%s-%s" $.Values.clusterName "karpenter" -}}
---
apiVersion: authorization.azure.upbound.io/v1beta1
kind: RoleAssignment
metadata:
  name:  "{{ .Values.clusterName }}-karpenter"
  labels:
    app: {{ $ResourceName }}
spec:
  forProvider:
    principalId: "431817a5-6fa9-4906-bf40-e4ad793f6f8e"
    principalType: ServicePrincipal
    roleDefinitionName: Contributor
    scope: "/subscriptions/{{ .Values.subscriptionId }}"
