{{- $ResourceName := printf "%s-%s" $.Values.clusterName "karpenter" -}}
{{- $principalId := (lookup "managedidentity.azure.upbound.io/v1beta1" "UserAssignedIdentity" "" $ResourceName).status.atProvider.principalId -}}
---
apiVersion: authorization.azure.upbound.io/v1beta1
kind: RoleAssignment
metadata:
  name:  "{{ .Values.clusterName }}-karpenter"
  labels:
    app: {{ $ResourceName }}
spec:
  forProvider:
    principalId: {{ $principalId }}
    principalType: ServicePrincipal
    roleDefinitionName: Contributor
    scope: "/subscriptions/{{ .Values.subscriptionId }}"
