{{- $ResourceName := printf "%s-%s" $.Values.clusterName "karpenter" -}}
---
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Values.namespaceName }}
  labels:
    "azure.workload.identity/use": 'true'
      #app: {{ $ResourceName }}
  annotations:
    "azure.workload.identity/client-id": "37f1e7eb-652e-46c2-9502-f140c884d72c"
