# Default values for karpenter-nodepool-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""
instanceProfile: ""
instanceWinProfile: ""
clusterName: ""

NodePools:
  Linux:
    - name: default
      nodeClassRef: al2023
      instanceCategory: '[c, m, r, t, z]'
      capacityType: '[on-demand]'
      instanceArch: '[amd64]'
      weight: 100
      taint: {}
      InstanceSize: '[medium, large, xlarge, 2xlarge, 4xlarge, 8xlarge]'
      InstanceSizeOperator: "In"
      expireAfter: 1440h
      disruption:
        consolidateAfter: 300s
        consolidationPolicy: WhenEmptyOrUnderutilized
        budgets:
        - nodes: "100%"
          reasons:
          - "Empty"
        - nodes: "25%"
          reasons:
          - "Underutilized"
        - schedule: "0 0 * * *"
          reasons: 
          - "Underutilized"
          nodes: "0"
          duration: 22h
        - nodes: "1"
          reasons:
          - "Drifted"
        - schedule: "0 0 * * *"
          reasons: 
          - "Drifted"
          nodes: "0"
          duration: 22h
    - name: large
      nodeClassRef: al2023-large
      instanceCategory: '["c", "m", "r", "t", "z"]'
      capacityType: '["on-demand"]'
      instanceArch: '["amd64"]'
      weight: 90
      taint:
        name: "large"
        effect: NoSchedule
        values: "true"
      InstanceSize: '["nano", "micro", "small", "medium"]'
      InstanceSizeOperator: "NotIn"
      expireAfter: 1440h
      disruption:
        consolidateAfter: 120s
        consolidationPolicy: WhenEmpty
        budgets:
        - nodes: "100%"
          reasons:
          - "Empty"
        - nodes: "25%"
          reasons:
          - "Underutilized"
        - schedule: "0 0 * * *"
          reasons: 
          - "Underutilized"
          nodes: "0"
          duration: 22h
        - nodes: "0"
          reasons:
          - "Drifted"
    - name: arm64
      nodeClassRef: al2023-arm64
      instanceCategory: '["c", "m", "r", "t"]'
      instanceArch: '["arm64"]'
      capacityType: '["on-demand"]'
      weight: 90
      taint:
        name: "arm64"
        effect: NoSchedule
        values: "true"
      InstanceSize: '["nano", "micro", "small"]'
      InstanceSizeOperator: "NotIn"
      expireAfter: 1440h
      disruption:
        consolidateAfter: 300s
        consolidationPolicy: WhenEmpty
        budgets:
        - nodes: "100%"
          reasons:
          - "Empty"
        - nodes: "25%"
          reasons:
          - "Underutilized"
        - schedule: "0 0 * * *"
          reasons: 
          - "Underutilized"
          nodes: "0"
          duration: 22h
        - nodes: "0"
          reasons:
          - "Drifted"
    - name: gpu
      nodeClassRef: al2023-gpu
      instanceCategory: '["g", "p"]'
      capacityType: '["on-demand"]'
      instanceArch: '["arm64", "amd64"]'
      weight: 50
      taint:
        name: "gpu"
        effect: NoSchedule
        values: "true"
      InstanceSize: '["nano", "micro", "small"]'
      InstanceSizeOperator: "NotIn"
      expireAfter: 168h
      disruption:
        consolidateAfter: 60s
        consolidationPolicy: WhenEmpty
        budgets:
        - nodes: "100%"
          reasons:
          - "Empty"
        - nodes: "25%"
          reasons:
          - "Underutilized"
        - schedule: "0 0 * * *"
          reasons: 
          - "Underutilized"
          nodes: "0"
          duration: 22h
        - nodes: "0"
          reasons:
          - "Drifted"
    - name: spot
      nodeClassRef: al2023-spot
      instanceCategory: '["c", "m", "r", "t", "z"]'
      instanceArch: '["arm64", "amd64"]'
      capacityType: '["spot"]'
      weight: 70
      taint:
        name: "spot"
        effect: NoSchedule
        values: "true"
      InstanceSize: '["nano", "micro", "small"]'
      InstanceSizeOperator: "NotIn"
      expireAfter: 1440h
      disruption:
        consolidateAfter: 300s
        consolidationPolicy: WhenEmpty
        budgets:
        - nodes: "100%"
          reasons:
          - "Empty"
        - nodes: "25%"
          reasons:
          - "Underutilized"
        - schedule: "0 0 * * *"
          reasons: 
          - "Underutilized"
          nodes: "0"
          duration: 22h
        - nodes: "0"
          reasons:
          - "Drifted"
    
  Windows:
    - name: windows2019
      nodeClassRef: windows2019
      instanceCategory: '["c", "m", "r", "t", "z"]'
      capacityType: '["on-demand"]'
      instanceArch: '["amd64"]'
      weight: 40
      taint: {}
      InstanceSize: '["nano", "micro", "small"]'
      InstanceSizeOperator: "NotIn"
      expireAfter: 1440h
      disruption:
        consolidateAfter: 900s
        consolidationPolicy: WhenEmpty
        budgets:
        - nodes: "100%"
          reasons:
          - "Empty"
        - schedule: "0 2 * * *"
          reasons:
          - "Underutilized"
          nodes: "0"
          duration: 22h
        - nodes: "0"
          reasons:
          - "Drifted"
    - name: windows2022
      nodeClassRef: windows2022
      instanceCategory: '["c", "m", "r", "t", "z"]'
      capacityType: '["on-demand"]'
      instanceArch: '["amd64"]'
      weight: 50
      taint: {}
      InstanceSize: '["nano", "micro", "small"]'
      InstanceSizeOperator: "NotIn"
      expireAfter: 1440h
      disruption:
        consolidateAfter: 900s
        consolidationPolicy: WhenEmpty
        budgets:
        - nodes: "100%"
          reasons:
          - "Empty"
        - schedule: "0 2 * * *"
          reasons: 
          - "Underutilized"
          nodes: "0"
          duration: 22h
        - nodes: "0"
          reasons:
          - "Drifted"

NodeClasses:
  Linux:
    - name: default
      nodePoolName: al2023
      amiFamily: al2023
      volumeSize: 150Gi
      volumeType: gp3
      internetFacing: false
      awsChina: false
      podCidr: true
    - name: large
      nodePoolName: al2023-large
      amiFamily: al2023
      volumeSize: 150Gi
      volumeType: gp3
      internetFacing: false
      awsChina: false
      podCidr: true
    - name: arm64
      nodePoolName: al2023-arm64
      amiFamily: al2023
      volumeSize: 150Gi
      volumeType: gp3
      internetFacing: false
      awsChina: false
      podCidr: true
    - name: gpu
      nodePoolName: al2023-gpu
      amiFamily: al2023
      volumeSize: 150Gi
      volumeType: gp3
      internetFacing: false
      awsChina: false
      podCidr: true
    - name: spot
      nodePoolName: al2023-spot
      amiFamily: al2023
      volumeSize: 150Gi
      volumeType: gp3
      internetFacing: false
      awsChina: false
      podCidr: true
  Windows:
    - name: windows2019
      nodePoolName: windows2019
      amiFamily: windows2019
      volumeSize: 150Gi
      volumeType: gp3
      internetFacing: false
      windowsBuild: 10.0.17763
      runtimeClassName: windows-server-2019
    - name: windows2022
      nodePoolName: windows2022
      amiFamily: windows2022
      volumeSize: 150Gi
      volumeType: gp3
      internetFacing: false
      windowsBuild: 10.0.20348
      runtimeClassName: windows-server-2022