apiVersion: v2
name: external-secret-stack
version: 0.4.2
description: Helm chart for Custom ESO resources (secretstores, clusterstores, permissions). Requires the external secrets operator and crds.
icon: https://raw.githubusercontent.com/external-secrets/external-secrets/main/assets/eso-logo-large.png
