apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-resources-blacklist
  annotations:
    policies.kyverno.io/title: Restrict access to specificy resources
    policies.kyverno.io/category: Security
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: ClusterRole, Role, RBAC
    kyverno.io/kyverno-version: 1.7.0
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/description: >-
      Specific resources are forbidden for security reasons (privilege escalation etc.)
      This policy blocks any Role or ClusterRole that contains resources which could compromise security.      
spec:
  validationFailureAction: {{ .Values.policies.validate.RestrictResourcesBlacklist }}
  failurePolicy: Fail
  background: false
  rules:
    - name: resources-blacklist
      match:
        any:
        - resources:
            kinds:
            - Role
            - ClusterRole
            namespaceSelector:
              matchExpressions:
              - key: enerkube-managed
                operator: In
                values:
                - "true"
        - resources:
            kinds:
            - Role
            - ClusterRole
            namespaces:
              - "default"
      preconditions:
        all:
        - key: "{{`{{`}} request.operation {{`}}`}}"
          operator: AnyIn
          value:
          - CREATE
          - UPDATE
          - DELETE
      exclude:
        any:
        - clusterRoles:
          - cluster-admin
        - subjects:
          - kind: Group
            name: system:masters
      validate:
        message: "Access to this resources is forbidden."
        deny:
          conditions:
            any:
            - key: 
                - "alertmanagerconfigs"
                - "alertmanagers"
                - "probes"
                - "prometheuses"
                - "thanosrulers"
                - "podsecuritypolicies"
                - "securitygrouppolicies"
                - "ingressclasses"
                - "clusterrolebindings"
                - "clusterroles"
                - "volumesnapshotclasses"
                - "blockaffinities"
                - "volumesnapshotcontents"
                - "ipamblocks"
                - "ipamconfigs"
                - "ipamhandles"
                - "bgpconfigurations"
                - "bgppeers"
                - "caliconodestatuses"
                - "clusterinformations"
                - "felixconfigurations"
                - "globalnetworkpolicies"
                - "globalnetworksets"
                - "hostendpoints"   
                - "ippools"       
                - "ipreservations"
                - "kubecontrollersconfigurations"
                - "networksets" 
                - "profiles"                   
              operator: AnyIn
              value: "{{`{{ request.object.rules[].resources[] }}`}}"

