{{- if .Values.policies.mutate.enerkubeAddDefaultNodeSelector -}}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: mutating-add-default-nodeselector
  annotations:
    policies.kyverno.io/title: Add nodeSelector
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      The nodeSelector field uses labels to select the node on which a Pod can be scheduled.
      This can be useful when Pods have specific needs that only certain nodes in a cluster can provide.
      This policy adds the nodeSelector field to a Pod spec and configures it with labels `foo` and `color`.      
spec:
  rules:
    - name: add-default-nodeselector
      match:
        resources:
          kinds:
          - Pod
          - Job
          - CronJob
          - Deployment
      exclude:
        resources:
          selector:
            matchLabels:
              strimzi.io/cluster: cipstream
      mutate:
        patchStrategicMerge:
          spec:
            nodeSelector:
              +(kubernetes.io/os): linux
      preconditions:
        all:
        - key: "{{`{{  request.operation }}`}}"
          operator: Equals
          value: CREATE
{{- end -}}
