{{- if .Values.policies.mutate.enerkubeAddDefaultCapabilitiesToNamespaces -}}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: mutating-add-default-capabilities-to-namespaces
  annotations:
    policies.kyverno.io/title: Add Default Capabilities to selected Namespaces
    policies.kyverno.io/category: Security
    policies.kyverno.io/subject: Pod
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/description: >-
      This policy adds the Default Capabilities field to a Pod spec to selected namespaces if not defined.    
spec:
  rules:
    - name: add-default-capabilities-to-namespaces
      match:
        any:
        - resources:
            kinds:
            - Pod
            namespaces: 
            {{- range .Values.policies.mutate.enerkubeAddDefaultCapabilitiesToNamespaces }}
              - {{ . | quote }}
            {{- end }}
      preconditions:
        all:
        - key: "{{`{{`}} request.operation {{`}}`}}"
          operator: AnyIn
          value:
            - CREATE
            - UPDATE
      mutate:
        foreach:
        - list: request.object.spec.containers[]
          preconditions:
            all:
            - key: ALL
              operator: AnyNotIn
              value: "{{`{{`}}element.securityContext.capabilities.drop[] || `[]` {{`}}`}}"
          patchesJson6902: |-
            - path: "/spec/containers/{{`{{`}}elementIndex{{`}}`}}/securityContext/capabilities/drop/-"
              op: add
              value: ALL
        - list: request.object.spec.initContainers[]
          preconditions:
            all:
            - key: ALL
              operator: AnyNotIn
              value: "{{`{{`}}element.securityContext.capabilities.drop[] || `[]` {{`}}`}}"
          patchesJson6902: |-
            - path: "/spec/initContainers/{{`{{`}}elementIndex{{`}}`}}/securityContext/capabilities/drop/-"
              op: add
              value: ALL
{{- end -}}
