apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: mutating-gpu-limit
  annotations:
    policies.kyverno.io/category: enerkube
    policies.kyverno.io/description: Sets GPU Limit on GPU nodes
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/title: Mutate GPU Limit on GPU nodes
    pod-policies.kyverno.io/autogen-controllers: none
spec:
  rules:
  - match:
      any:
      - resources:
          kinds:
          - Pod
          namespaceSelector:
            matchExpressions:
            - key: enerkube-managed
              operator: In
              values:
              - "true"
      - resources:
          kinds:
          - Pod
          namespaces:
          - default
    mutate:
      patchStrategicMerge:
        spec:
          containers:
          - (name): '*'
            resources:
              limits:
                +(nvidia.com/gpu): "1"
    name: mutate-gpu-limits-for-gpu-instance
    preconditions:
      all:
      - key: "{{`{{`}} request.object.spec.tolerations[].key || `[]` {{`}}`}}"
        operator: AnyIn
        value: gpu
      - key: "{{`{{`}} request.operation {{`}}`}}"
        operator: AnyIn
        value:
        - CREATE
    skipBackgroundRequests: true
  validationFailureAction: Audit
