{{- $UAIRandom := randAlphaNum 8 | nospace | lower -}}
{{- range $userIdentity := .Values.userIdentity }}
---
apiVersion: managedidentity.azure.upbound.io/v1beta1
kind: UserAssignedIdentity
metadata:
  annotations:
    meta.upbound.io/{{ .name }}-id: managedidentity/v1beta1/userassignedidentity
  labels:
    app: {{ .name }}
  name: "{{ .clusterName }}-{{ .name }}"
spec:
  forProvider:
    location: {{ .location }}
    name: "{{ .clusterName }}-{{ .name }}-{{ $UAIRandom }}"
    resourceGroupName: {{ .resourceGroup }}
---
apiVersion: managedidentity.azure.upbound.io/v1beta1
kind: FederatedIdentityCredential
metadata:
  name: "{{ .clusterName }}-{{ .name }}"
  labels:
    app: {{ .name }}
spec:
  forProvider:
    audience:
      - api://AzureADTokenExchange
    issuer: {{ .oidcUrl }}
    parentIdSelector:
      matchLabels:
        app: {{ .name }}
    resourceGroupName: {{ .resourceGroup }}
    subject: system:serviceaccount:{{ .namespaceName }}:{{ .serviceAccountName }}
{{- end }}
