{{- $namespaceName := .Values.namespaceName | required ".Values.namespaceName is required." -}}

apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: default-login-serviceaccount
  name: default-login-serviceaccount-token
  namespace:  {{ $namespaceName }}
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: read-only
  name: read-only-token
  namespace:  {{ $namespaceName }}
type: kubernetes.io/service-account-token

{{- if .Values.createPrivileged }}
---
apiVersion: v1
data:
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: privileged
  name: privileged-token
  namespace:  {{ $namespaceName }}
type: kubernetes.io/service-account-token
{{- end }}