{{- $namespaceName := .Values.namespaceName | required ".Values.namespaceName is required." -}}

{{- if .Values.createDefault }}
apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  name: default-login-serviceaccount
  namespace: {{ $namespaceName }}
{{- end }}
{{- if .Values.createReadOnly }}
---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: read-only
  namespace: {{ $namespaceName }}
{{- end }}
{{- if .Values.createPrivileged }}
---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: privileged
  namespace: {{ $namespaceName }}
{{- end }}