---
apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  name: eso-validating-crd-access-exception-subject
  namespace: enerkube-system
spec:
  background: false
  exceptions:
    - policyName: validating-crd-access
      ruleNames:
        - check-crd-access
  match:
    all:
      - subjects:
          - kind: ServiceAccount
            name: external-secrets-cert-controller
            namespace: enerkube-system
      - resources:
          kinds:
            - CustomResourceDefinition
          selector:
            matchLabels:
              external-secrets.io/component: controller
