{{- $ResourceName := printf "%s-%s" $.Values.roleAssignment.clusterName $.Values.roleAssignment.name -}}
{{- $principalId := (lookup "managedidentity.azure.upbound.io/v1beta1" "UserAssignedIdentity" "" $ResourceName).status.atProvider.principalId -}}
{{- range $roleAssignment := .Values.roleAssignment }}
---
apiVersion: authorization.azure.upbound.io/v1beta1
kind: RoleAssignment
metadata:
  name:  "{{ .clusterName }}-{{ .name }}-{{ .rolename }}"
  labels:
    app: {{ $ResourceName }}
spec:
  forProvider:
    principalId: {{ $principalId }}
    principalType: ServicePrincipal
    roleDefinitionName: {{ .rolename }}
    scope: "/subscriptions/{{ .subscriptionId }}"
{{- end }}