{{- $UAIRandom := randAlphaNum 8 | nospace | lower -}}
{{- $ResourceName := printf "%s-%s" $.Values.clusterName $.Values.name -}}
{{- $principalId := (lookup "managedidentity.azure.upbound.io/v1beta1" "UserAssignedIdentity" "" $ResourceName).status.atProvider.principalId -}}
{{- range $roleAssignment := .Values.roleAssignment }}
---
apiVersion: authorization.azure.upbound.io/v1beta1
kind: RoleAssignment
metadata:
  name:  "{{ $.Values.clusterName }}-{{ $.Values.name }}-{{ .rolename | nospace | lower }}"
  labels:
    app: {{ $ResourceName }}
spec:
  forProvider:
    name: "{{ $.Values.clusterName }}-{{ $.Values.name }}-{{ .rolename | nospace | lower }}-{{ $UAIRandom }}"
    principalId: {{ $principalId }}
    principalType: ServicePrincipal
    roleDefinitionName: {{ .rolename }}
    scope: "/subscriptions/{{ $.Values.subscriptionId }}"
{{- end }}