apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: validating-psp-check-supplemental-groups
  annotations:
    policies.kyverno.io/title: Check supplementalGroups
    policies.kyverno.io/category: PSP Migration
    policies.kyverno.io/severity: medium
    kyverno.io/kyverno-version: 1.6.0
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/subject: Pod
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/description: >-
      Supplemental groups control which group IDs containers add and can coincide with
      restricted groups on the host. Pod Security Policies (PSP) allowed a range of
      these group IDs to be specified which were allowed. This policy ensures any Pod
      may only specify supplementalGroup IDs between 1000 and above.
spec:
  validationFailureAction: {{ .Values.policies.validate.CheckSupplementalGroups }}
  failurePolicy: Fail
  background: false
  rules:
    - name: check-supplemental-group-ranges
      match:
        any:
        - resources:
            kinds:
            - Pod
            namespaceSelector:
              matchExpressions:
              - key: enerkube-managed
                operator: In
                values:
                - "true"
        - resources:
            kinds:
            - Pod
            namespaces:
              - "default"
      preconditions:
        all:
        - key: "{{`{{ request.operation }}`}}"
          operator: In
          value:
          - CREATE
          - UPDATE
      validate:
        message: Any supplementalGroup ID must be within the range 1000 and above..
        pattern:
          spec:
            =(securityContext):
              =(supplementalGroups): ">=1000"