apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  annotations:
    kyverno.io/kubernetes-version: 1.22-1.23
    kyverno.io/kyverno-version: 1.6.0
    policies.kyverno.io/category: Sample
    policies.kyverno.io/description: Containers should be forbidden from running with
      a root primary or supplementary GID. This policy ensures the `runAsGroup`, `supplementalGroups`,
      and `fsGroup` fields are set to a number greater than zero (i.e., non root).
      A known issue prevents a policy such as this using `anyPattern` from being persisted
      properly in Kubernetes 1.23.0-1.23.2.
    policies.kyverno.io/minversion: 1.3.6
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod, Deployment, StatefulSet, DaemonSet
    pod-policies.kyverno.io/autogen-controllers: none
  name: validating-require-non-root-groups
spec:
  validationFailureAction: {{ .Values.policies.validate.RequireRunAsNonRootGroups }}
  background: true
  failurePolicy: Fail
  rules:
    - name: check-runasgroup
      exclude:
          any:
          - resources:
              kinds:
              - Pod
              namespaceSelector:
                matchExpressions:
                - key: enerkube-kyverno-runasroot-groups
                  operator: In
                  values:
                  - "true"
      match:
          any:
          - resources:
              kinds:
              - Pod
              namespaceSelector:
                matchExpressions:
                - key: enerkube-managed
                  operator: In
                  values:
                  - "true"
          - resources:
              kinds:
              - Pod
              namespaces:
              - "default"
      preconditions:
        all:
        - key: "{{`{{`}} request.operation {{`}}`}}"
          operator: AnyIn
          value:
          - CREATE
      validate:
        anyPattern:
        - spec:
            =(ephemeralContainers):
            - =(securityContext):
                =(runAsGroup): '>0'
            =(initContainers):
            - =(securityContext):
                =(runAsGroup): '>0'
            containers:
            - =(securityContext):
                =(runAsGroup): '>0'
            securityContext:
                runAsGroup: '>0'
        - spec:
            =(ephemeralContainers):
            - securityContext:
                runAsGroup: '>0'
            =(initContainers):
            - securityContext:
                runAsGroup: '>0'
            containers:
            - securityContext:
                runAsGroup: '>0'
        message: >-
          Running with root group IDs is disallowed. The fields spec.securityContext.runAsGroup,
          spec.containers[*].securityContext.runAsGroup, spec.initContainers[*].securityContext.runAsGroup,
          and spec.ephemeralContainers[*].securityContext.runAsGroup must be set to a value greater than zero.
    - name: check-supplementalgroups
      exclude:
        any:
        - resources:
            kinds:
            - Pod
            namespaceSelector:
              matchExpressions:
              - key: enerkube-kyverno-runasroot-groups
                operator: In
                values:
                - "true"
      match:
        any:
        - resources:
            kinds:
            - Pod
            namespaceSelector:
              matchExpressions:
              - key: enerkube-managed
                operator: In
                values:
                - "true"
        - resources:
            kinds:
            - Pod
            namespaces:
            - "default"
      preconditions:
        all:
        - key: "{{`{{`}} request.operation {{`}}`}}"
          operator: AnyIn
          value:
          - CREATE
      validate:
        message: Containers cannot run with a root primary or supplementary GID. The
          field spec.securityContext.supplementalGroups must be unset or set to a value
          greater than zero.
        pattern:
          spec:
            =(securityContext):
              =(supplementalGroups): '>0'
    - name: check-fsgroup
      exclude:
        any:
        - resources:
            kinds:
            - Pod
            namespaceSelector:
              matchExpressions:
              - key: enerkube-kyverno-runasroot-groups
                operator: In
                values:
                - "true"
      match:
        any:
        - resources:
            kinds:
            - Pod
            namespaceSelector:
              matchExpressions:
              - key: enerkube-managed
                operator: In
                values:
                - "true"
        - resources:
            kinds:
            - Pod
            namespaces:
            - "default"
      preconditions:
        all:
        - key: "{{`{{`}} request.operation {{`}}`}}"
          operator: AnyIn
          value:
          - CREATE
      validate:
        message: Containers cannot run with a root primary or supplementary GID. The
          field spec.securityContext.fsGroup must be unset or set to a value greater
          than zero.
        pattern:
          spec:
            =(securityContext):
              =(fsGroup): '>0'