apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: validating-disallow-efs-profisioner
  annotations:
    policies.kyverno.io/title: Disallow EFS Profisioner
    policies.kyverno.io/category: Other
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: PersistentVolumeClaim, StatefulSet
    policies.kyverno.io/description: >-
      PersistentVolumeClaims (PVCs) and StatefulSets may optionally define a StorageClass
      to dynamically provision storage. EFS-Provisioner is deprecated and should not be 
      used anymore
spec:
  validationFailureAction: {{ .Values.policies.validate.enerkubeDisallowEfsProvisioner }}
  background: true
  rules:
  - name: pvc-deny-efs-storageclass
    match:
      any:
      - resources:
          kinds:
          - PersistentVolumeClaim
    validate:
      message: "EFS-Provisioner is deprecated and should not be used anymore.
        Use EFS CSI Driver instead."
      pattern:
        spec:
          storageClassName: "!aws-efs*"
    preconditions:
      all:
      - key: "{{`{{`}} request.operation {{`}}`}}"
        operator: AnyIn
        value:
        - CREATE
        - UPDATE
  - match:
      any:
      - resources:
          kinds:
          - StatefulSet
    name: sts-deny-efs-storageclass
    preconditions:
      all:
      - key: "{{`{{`}} request.operation {{`}}`}}"
        operator: AnyIn
        value:
        - CREATE
        - UPDATE
    validate:
      message: EFS-Provisioner is deprecated and should not be used anymore. Use EFS
        CSI Driver instead.
      pattern:
        =(spec):
          =(volumeClaimTemplates):
          - =(spec):
              =(storageClassName): '!aws-efs*'
