{{- if .Values.policies.enable.RestrictSecretStore -}}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-secretstore
  annotations:
    policies.kyverno.io/category: enerkube
    policies.kyverno.io/description: "SecretStore Provider must be vault"
    policies.kyverno.io/subject: SecretStore
    policies.kyverno.io/title: Restrict SecretStore
spec:
  validationFailureAction: Enforce
  background: false
  rules:
  - name: restrict-secretstore
    match:
      any:
      - resources:
          kinds:
          - external-secrets.io/*/SecretStore
          namespaceSelector:
            matchExpressions:
            - key: enerkube-managed
              operator: In
              values:
              - "true"
      - resources:
          kinds:
          - external-secrets.io/*/SecretStore
          namespaces:
            - "default"
    exclude:
      any:
      - clusterRoles:
        - cluster-admin
      - subjects:
        - kind: Group
          name: system:masters
    preconditions:
      all:
      - key: "{{`{{`}} request.operation {{`}}`}}"
        operator: AnyIn
        value:
        - CREATE
        - UPDATE
        - DELETE
    validate:
      message: "SecretStore must be of type vault"
      pattern:
        spec:
          provider:
            vault: {}
{{- end -}}
