{{- if .Values.policies.mutate.enerkubeAddDefaultNamespaceLabels -}}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: mutating-add-default-namespace-labels
  annotations:
    policies.kyverno.io/title: Add Default Namspace Labels
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Label
    policies.kyverno.io/description: >-
      Labels are used as an important source of metadata describing objects in various ways
      or triggering other functionality. Labels are also a very basic concept and should be
      used throughout Kubernetes. This policy performs a simple mutation which adds a label
      `foo=bar` to Pods, Services, ConfigMaps, and Secrets.      
spec:
  rules:
    - name: add-default-namespace-labels
      match:
        resources:
          kinds:
          - Namespace
      preconditions:
        all:
        - key: "{{`{{ request.operation }}`}}"
          operator: In
          value:
            - CREATE
            - UPDATE
        - key: "{{`{{ request.object.metadata.labels.tekton }}`}}"
          operator: In
          value: "true"
      mutate:
        patchStrategicMerge:
          metadata:
            labels:
              enerkube-managed: "true"
{{- end -}}