apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: validating-restrict-binding-default-sa
  annotations:
    policies.kyverno.io/title: Restrict Binding to default SA
    policies.kyverno.io/category: Security
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: RoleBinding, ClusterRoleBinding
    kyverno.io/kyverno-version: 1.6.2
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/description: >-
      The default SA should not be used by customized via RoleBindings since the default is available for everyone.
      This policy prevents binding to the default SA ClusterRole in RoleBinding or ClusterRoleBinding resources.      
spec:
  validationFailureAction: {{ .Values.policies.validate.enerkubeRestrictBindingDefaultSA }}
  background: true
  rules:
    - name: sa-bindings
      match:
        any:
        - resources:
            kinds:
              - RoleBinding
              - ClusterRoleBinding
      exclude:
        resources:
          names: 
          - "default-reader-clusterrole-binding-*"
      preconditions:
        all:
        - key: "{{`{{`}} request.operation {{`}}`}}"
          operator: AnyIn
          value:
          - CREATE
          - UPDATE
      validate:
        message: "Binding to default sa is not allowed."
        pattern:
          =(subjects):
          - name: "!default"