apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: validating-restrict-binding-clusteradmin
  annotations:
    policies.kyverno.io/title: Restrict Binding to Cluster-Admin
    policies.kyverno.io/category: Security
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: RoleBinding, ClusterRoleBinding, RBAC
    kyverno.io/kyverno-version: 1.6.2
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/description: >-
      The cluster-admin ClusterRole allows any action to be performed on any resource
      in the cluster and its granting should be heavily restricted. This
      policy prevents binding to the cluster-admin ClusterRole in
      RoleBinding or ClusterRoleBinding resources.
spec:
  validationFailureAction: {{ .Values.policies.validate.RestrictBindingClusteradmin }}
  failurePolicy: Fail
  background: true
  rules:
    - name: restrict-binding-clusteradmin
      match:
        any:
        - resources:
            kinds:
            - RoleBinding
            - ClusterRoleBinding
      exclude:
        resources:
          names: 
          - cluster-admin
          - admin
          - flux-applier
      preconditions:
        all:
        - key: "{{`{{`}} request.operation {{`}}`}}"
          operator: AnyIn
          value:
          - CREATE
          - UPDATE
      validate:
        message: "Binding to cluster-admin is not allowed."
        pattern:
          roleRef: 
            name: "!cluster-admin"
