# enerkube Chart specificc Values
userIdentity:
  - name: "tbd"
    namespaceName: "tbd"
    serviceAccountName: "tbd"
    clusterName: tbd
    subscriptionId: tbd
    location: tbd
    oidcUrl: tbd
    resourceGroup: tbd