{{- $ResourceName := printf "%s-%s" $.Values.clusterName "karpenter" -}}
{{- $clientId := (lookup "managedidentity.azure.upbound.io/v1beta1" "UserAssignedIdentity" "" $ResourceName).status.atProvider.clientId -}}
---
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Values.namespaceName }}
  labels:
    "azure.workload.identity/use": 'true'
    app: {{ $ResourceName }}
  annotations:
    "azure.workload.identity/client-id": {{ $clientId }}
