apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Values.namespaceName }}
  annotations:
    "eks.amazonaws.com/role-arn": "arn:aws:iam::{{ .Values.accountId }}:role/{{ .Values.clusterName }}-karpenter"
