# Default values for karpenter-nodepool-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""
clusterName: ""
location: ""

NodePools:
  Linux:
    - name: default
      nodeClassRef: ubuntu
      skuFamily: '["A", "B", "D", "DC", "F", "FX", "EB", "EC", "M" ]'
      capacityType: '[on-demand]'
      instanceArch: '[amd64]'
      weight: 100
      taint: {}
      # InstanceSize: '[medium, large, xlarge, 2xlarge, 4xlarge, 8xlarge]'
      # InstanceSizeOperator: "In"
      expireAfter: 1440h
      disruption:
        consolidateAfter: 300s
        consolidationPolicy: WhenEmptyOrUnderutilized
        budgets:
        - nodes: "100%"
          reasons:
          - "Empty"
        - nodes: "25%"
          reasons:
          - "Underutilized"
        - schedule: "0 0 * * *"
          reasons: 
          - "Underutilized"
          nodes: "0"
          duration: 22h
        - nodes: "1"
          reasons:
          - "Drifted"
        - schedule: "0 0 * * *"
          reasons: 
          - "Drifted"
          nodes: "0"
          duration: 22h
    - name: large
      nodeClassRef: ubuntu-large
      skuFamily: '["A", "B", "D", "DC", "F", "FX", "EB", "EC", "M" ]'
      capacityType: '["on-demand"]'
      instanceArch: '["amd64"]'
      weight: 90
      taint:
        name: "large"
        effect: NoSchedule
        values: "true"
      # InstanceSize: '["nano", "micro", "small", "medium"]'
      # InstanceSizeOperator: "NotIn"
      expireAfter: 1440h
      disruption:
        consolidateAfter: 120s
        consolidationPolicy: WhenEmpty
        budgets:
        - nodes: "100%"
          reasons:
          - "Empty"
        - nodes: "25%"
          reasons:
          - "Underutilized"
        - schedule: "0 0 * * *"
          reasons: 
          - "Underutilized"
          nodes: "0"
          duration: 22h
        - nodes: "0"
          reasons:
          - "Drifted"
    - name: arm64
      nodeClassRef: ubuntu-arm64
      skuFamily: '["B", "D", "E" ]'
      instanceArch: '["arm64"]'
      capacityType: '["on-demand"]'
      weight: 90
      taint:
        name: "arm64"
        effect: NoSchedule
        values: "true"
      # InstanceSize: '["nano", "micro", "small"]'
      # InstanceSizeOperator: "NotIn"
      expireAfter: 1440h
      disruption:
        consolidateAfter: 300s
        consolidationPolicy: WhenEmpty
        budgets:
        - nodes: "100%"
          reasons:
          - "Empty"
        - nodes: "25%"
          reasons:
          - "Underutilized"
        - schedule: "0 0 * * *"
          reasons: 
          - "Underutilized"
          nodes: "0"
          duration: 22h
        - nodes: "0"
          reasons:
          - "Drifted"
    - name: gpu
      nodeClassRef: ubuntu-gpu
      skuFamily: '["NC", "ND", "NG", "NV" ]'
      capacityType: '["on-demand"]'
      instanceArch: '["arm64", "amd64"]'
      weight: 50
      taint:
        name: "gpu"
        effect: NoSchedule
        values: "true"
      # InstanceSize: '["nano", "micro", "small"]'
      # InstanceSizeOperator: "NotIn"
      expireAfter: 168h
      disruption:
        consolidateAfter: 60s
        consolidationPolicy: WhenEmpty
        budgets:
        - nodes: "100%"
          reasons:
          - "Empty"
        - nodes: "25%"
          reasons:
          - "Underutilized"
        - schedule: "0 0 * * *"
          reasons: 
          - "Underutilized"
          nodes: "0"
          duration: 22h
        - nodes: "0"
          reasons:
          - "Drifted"
    - name: spot
      nodeClassRef: ubuntu-spot
      skuFamily: '["A", "B", "D", "DC", "F", "FX", "E", "EB", "EC", "M" ]'
      instanceArch: '["arm64", "amd64"]'
      capacityType: '["spot"]'
      weight: 70
      taint:
        name: "spot"
        effect: NoSchedule
        values: "true"
      # InstanceSize: '["nano", "micro", "small"]'
      # InstanceSizeOperator: "NotIn"
      expireAfter: 1440h
      disruption:
        consolidateAfter: 300s
        consolidationPolicy: WhenEmpty
        budgets:
        - nodes: "100%"
          reasons:
          - "Empty"
        - nodes: "25%"
          reasons:
          - "Underutilized"
        - schedule: "0 0 * * *"
          reasons: 
          - "Underutilized"
          nodes: "0"
          duration: 22h
        - nodes: "0"
          reasons:
          - "Drifted"
    
NodeClasses:
  Linux:
    - name: default
      nodePoolName: ubuntu
      imageFamily: Ubuntu2204   # Ubuntu2204 or AzureLinux
      volumeSize: 150
    - name: large
      nodePoolName: ubuntu-large
      imageFamily: Ubuntu2204
      volumeSize: 150
    - name: arm64
      nodePoolName: ubuntu-arm64
      imageFamily: Ubuntu2204
      volumeSize: 150
    - name: gpu
      nodePoolName: ubuntu-gpu
      imageFamily: Ubuntu2204
      volumeSize: 150
    - name: spot
      nodePoolName: ubuntu-spot
      imageFamily: Ubuntu2204
      volumeSize: 150