{{- range $nodepool := .Values.NodePools.Linux }}
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: {{ .name }}
  annotations:
    nodepoolname: {{ .name }}
    kubernetes.io/description: "NodePool for Linux {{ .name }} workloads"
  labels:
    nodepoolname: {{ .name }}
    {{- include "karpenter-nodepool.labels" $ | nindent 4 }}
spec:
  template:
    spec:
      expireAfter: {{ $nodepool.expireAfter }}
      terminationGracePeriod: 12h
      {{- if .taint }}
      {{- with .taint }}
      taints:
        - key: {{ .name }}
          value: "{{ .values }}"
          effect: {{ .effect }}{{ end }}{{ end }}
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: {{ .instanceArch }}
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: {{ .capacityType }}
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: {{ .instanceCategory }}
        - key: "karpenter.k8s.aws/instance-family"
          operator: NotIn
          values: ["m7i-flex","c7i-flex"]
        - key: karpenter.k8s.aws/instance-size
          operator: {{ .InstanceSizeOperator }}
          values: {{ .InstanceSize }}
        {{- if ne .name "arm64" }}
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]{{ end }}
        - key: "nodepoolname"
          operator: In
          values: ["{{ .name }}"]
      {{- if .taint }}
      {{- with .taint }}
        - key: {{ .name }}
          operator: In
          values: ["{{ .values }}"]
        - key: "taint"
          operator: In
          values: ["true"]{{ end }}{{ end }}
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: {{ .nodeClassRef }}
  disruption: {{ .disruption | toYaml | nindent 4 }}
  weight: {{ $nodepool.weight }}
{{- end }}
