name: Chart github.com

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'charts/**'
jobs:
  release_chart:
    runs-on: ubuntu-latest
    #container:
    #  image: dschunack/standard-init-container:1.0.0
    #  options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Add repositories
        run: |
          for dir in $(ls -d charts/*/*/); do
            helm dependency list $dir 2> /dev/null | tail +2 | head -n -1 | awk '!/oci/ { print "helm repo add " $1 " " $3 }' | while read cmd; do $cmd; done
          done

      - name: Run chart-releaser for base charts (without dependencies)
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: charts/base
          config: cr-github-com.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Sleep
        run: |
          sleep 60

      - name: Run chart-releaser for stacks (with dependencies)
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: charts/stacks
          config: cr-github-com.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
